//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluidOne.ClientTesting.Dash.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSCode
    {
        public int UserAccountID { get; set; }
        public string Code { get; set; }
        public bool Verifyed { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
