//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluidOne.ClientTesting.Dash.PageObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttempt
    {
        public int LoginAttemptID { get; set; }
        public Nullable<int> UserAccountID { get; set; }
        public string AttemptedAccount { get; set; }
        public string AttemptedEmail { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
        public System.DateTime InsertedDate { get; set; }
        public bool Success { get; set; }
        public Nullable<int> ImpersonaterId { get; set; }
        public int LockNumber { get; set; }
        public Nullable<int> LoginResponseCodeID { get; set; }
        public bool Invalidated { get; set; }
    
        public virtual UserAccount UserAccount { get; set; }
    }
}
