//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FluidOne.ClientTesting.Dash.PageObjects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalEntities2 : DbContext
    {
        public PortalEntities2()
            : base("name=PortalEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<LoginAttempt> LoginAttempts { get; set; }
        public DbSet<SMSCode> SMSCodes { get; set; }
        public DbSet<UserAccount> UserAccounts { get; set; }
        public DbSet<UserMachineInfo> UserMachineInfoes { get; set; }
    }
}
